VALID_TAGS = [

    # ── Working with Functions ─────────────────────────────────────────────
    "simplifying expressions",
    "index laws",
    "expanding",
    "factorising",
    "algebraic fractions",
    "linear equations",
    "quadratic equations",
    "simultaneous equations",
    "completing the square",
    "types of numbers",
    "decimals percentages fractions",
    "rounding",
    "surds",
    "types of relations",
    "function notation",
    "piecewise functions",
    "domain and range",
    "break even point",
    "interval notation",
    "odd even functions",
    "composite functions",

    # ── Graphs ────────────────────────────────────────────────────────────
    "linear graphs",
    "gradient of line",
    "parallel perpendicular lines",
    "equation of line",
    "quadratic graphs",
    "points of intersection",
    "discriminant",
    "circle semicircle graphs",
    "polynomial graphs",
    "square root graphs",
    "hyperbolic graphs",
    "direct inverse variation",
    "shifting graphs",
    "reflecting graphs",
    "absolute value graphs",
    "reciprocating graphs",
    "adding subtracting graphs",
    "square rooting graphs",
    "inverse function sketch",

    # ── Trigonometry ──────────────────────────────────────────────────────
    "sohcahtoa",
    "exact trig ratios",
    "angles elevation depression",
    "bearings",
    "sine rule",
    "cosine rule",
    "area sine formula",
    "trig 3d",
    "radians",
    "arc length",
    "sector segment area",
    "trigonometric equations",
    "trig identities",
    "angles any magnitude",
    "trig graphs",
    "inverse trig functions",
    "compound angles",
    "double angles",
    "products to sums",
    "t results",

    # ── Logarithms and Exponentials ───────────────────────────────────────
    "exponential graphs",
    "log laws",
    "logarithmic scales",
    "eulers number",
    "differentiating exponentials",
    "using ln",
    "sketching logarithms",
    "integrating exponentials",
    "integrating logarithm",

    # ── Differentiation ───────────────────────────────────────────────────
    "continuity",
    "first principles",
    "gradient function",
    "differentiability",
    "rates of change",
    "differentiating powers",
    "product rule",
    "quotient rule",
    "chain rule",
    "tangents normals",
    "differentiating trig",
    "differentiating logarithms",
    "differentiating inverse trig",
    "implicit differentiation",

    # ── Applications of Differentiation ──────────────────────────────────
    "increasing decreasing",
    "stationary points",
    "nature of points",
    "concavity",
    "points of inflection",
    "interpreting derivatives",
    "max min value",
    "optimisation",
    "velocity speed",
    "motion differentiation",
    "displacement velocity acceleration",

    # ── Graphing Techniques ───────────────────────────────────────────────
    "dilations enlargements",
    "limits to infinity",
    "curve sketching",
    "linear inequalities",
    "quadratic inequalities",
    "solving inequalities",

    # ── Integral Calculus ─────────────────────────────────────────────────
    "primitive functions",
    "indefinite integrals",
    "definite integrals",
    "integral properties",
    "integrating trig",
    "integrating inverse trig",
    "reverse chain rule",
    "trapezoidal rule",
    "areas x axis",
    "areas y axis",
    "areas between curves",
    "motion integration",

    # ── Further Integration (Ext 2) ───────────────────────────────────────
    "algebraic manipulation",
    "dividing before integrating",
    "integration by substitution",
    "trig substitution",
    "partial fractions",
    "quadratic denominators",
    "rationalising numerator",
    "integration by parts",
    "trigonometric integrals",
    "integration by reduction",

    # ── Financial Mathematics ─────────────────────────────────────────────
    "simple interest",
    "compound interest",
    "arithmetic sequences",
    "geometric sequences",
    "AP definition",
    "AP nth term",
    "AP sum",
    "GP definition",
    "GP nth term",
    "GP sum",
    "limiting sum",
    "superannuation",
    "loan repayments",

    # ── Probability ───────────────────────────────────────────────────────
    "probability set notation",
    "venn diagrams",
    "multi stage events",
    "conditional probability",
    "independent events",
    "discrete continuous variables",
    "probability distributions",
    "expected value",
    "standard deviation",
    "variance",

    # ── Descriptive Statistics ────────────────────────────────────────────
    "five number summary",
    "displaying data",
    "bivariate data",
    "correlation",
    "regression line",
    "relative frequency",
    "cumulative distribution",
    "probability density",
    "normal distribution",
    "continuous expected value",

    # ── Polynomials (Ext 1) ───────────────────────────────────────────────
    "polynomial definitions",
    "dividing polynomials",
    "remainder factor theorem",
    "sum product roots",
    "multiple zeroes",

    # ── Combinatorics (Ext 1) ─────────────────────────────────────────────
    "number of outcomes",
    "arrangements",
    "factorial notation",
    "combinations",
    "binomial theorem",

    # ── Differential Equations (Ext 1) ────────────────────────────────────
    "defining diff equations",
    "initial value problem",
    "first order DE",
    "logistic equation",

    # ── Binomial Distribution (Ext 1) ─────────────────────────────────────
    "binomial probability",

    # ── Proof (Ext 2) ─────────────────────────────────────────────────────
    "language of proof",
    "divisibility proofs",
    "proof by contradiction",
    "inequalities proof",
    "sigma notation",
    "mathematical induction",

    # ── Vectors (Ext 2) ───────────────────────────────────────────────────
    "3d vectors",
    "dot product",
    "projection of vectors",
    "vector proofs",
    "vector equation line",
    "vector equation circle",

    # ── Complex Numbers (Ext 2) ───────────────────────────────────────────
    "using i",
    "realising denominator",
    "real imaginary parts",
    "complex square roots",
    "modulus argument form",
    "exponential form",
    "conjugate root theorem",
    "curves regions z",
    "complex polynomials",
    "de moivres theorem",
    "complex number vectors",
    "roots of unity",

    # ── Mechanics (Ext 2) ─────────────────────────────────────────────────
    "simple harmonic motion",
    "motion without resistance",
    "resisted motion",
    "projectile cartesian",
    "projectile resistance",
    "forces",

    # ── General ───────────────────────────────────────────────────────────
    "worded problem",
    "multi step",
    "proof",
    "geometry",
    "measurement",
]